name: change-version  
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with: 
        ref: ${{ steps.extract_branch.outputs.branch }}
    - name: Create local changes
      run: |
        sed -i 's@version.*@version: ${{ steps.extract_branch.outputs.branch }}@g' test.yaml
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Adapt Chart Version to Branch" -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}:  
        branch:: ${{ steps.extract_branch.outputs.branch }}
